import {lessons} from '../content/lessons';
import {chapters,workshops} from '../content/workshops';
import type {ProgressApi} from '../progress/useProgress';
import LessonRunner from '../learning/LessonRunner';
export default function LearnView({api,onPrint}:{api:ProgressApi;onPrint:(ids:string[])=>void}){
 const current=lessons.find(l=>l.id===api.progress.cursor?.lessonId)??lessons[0],index=lessons.indexOf(current);
 const chapterOf=(id:string)=>workshops.find(w=>w.id===id)?.chapter??'foundations';
 const chapterId=chapterOf(current.id),chapter=chapters.find(c=>c.id===chapterId)!;
 const available=(i:number)=>i===0||chapterOf(lessons[i-1].id)!==chapterOf(lessons[i].id)||api.progress.completedLessonIds.includes(lessons[i-1].id)||api.progress.completedLessonIds.includes(lessons[i].id)||lessons[i].id===api.progress.cursor?.lessonId;
 const next=()=>{const target=lessons[Math.min(index+1,lessons.length-1)];api.setCursor({lessonId:target.id,step:0});};
 const selectChapter=(id:string)=>{const group=lessons.filter(l=>chapterOf(l.id)===id);const nextLesson=group.find(l=>!api.progress.completedLessonIds.includes(l.id))??group[0];api.setCursor({lessonId:nextLesson.id,step:0});};
 return <><header className="page-header"><div className="between heading-meta"><p className="eyebrow">THE SCRIBE’S COURSE / CHAPTER {chapter.number}</p><span className="badge">{api.progress.completedLessonIds.length} / {lessons.length} lessons</span></div><h1>{chapter.title}.</h1><p className="muted">{chapter.description}</p></header>
 <nav className="chapter-nav" aria-label="Course chapters">{chapters.map(c=>{const ids=lessons.filter(l=>chapterOf(l.id)===c.id).map(l=>l.id),done=ids.filter(id=>api.progress.completedLessonIds.includes(id)).length;return <button key={c.id} aria-current={c.id===chapterId?'page':undefined} onClick={()=>{if(c.id!==chapterId)selectChapter(c.id);}}><span className="chapter-numeral">{c.number}</span><span>{c.title}<small>{done} / {ids.length} completed</small></span></button>;})}</nav>
 <div className="learn-layout"><section className="panel lesson-panel"><div className="lesson-heading"><span className="eyebrow">LESSON {String(index+1).padStart(2,'0')}</span><h2>{current.title}</h2></div><LessonRunner key={current.id} lesson={current} progressApi={api} onNextLesson={next} onPrint={onPrint}/></section><aside className="course-path"><div className="path-header"><h2>In this chapter</h2></div><ol>{lessons.map((l,i)=>{if(chapterOf(l.id)!==chapterId)return null;const done=api.progress.completedLessonIds.includes(l.id),enabled=available(i);return <li key={l.id}><button disabled={!enabled} className={'course-row '+(current.id===l.id?'current':'')} onClick={()=>{if(current.id!==l.id)api.setCursor({lessonId:l.id,step:0});}} aria-current={current.id===l.id?'step':undefined}><span className={'step-number '+(done?'done':'')}>{done?'✓':String(i+1).padStart(2,'0')}</span><span>{l.title}<small>{l.kind==='signs'?l.signIds.length+' signs':l.kind==='intro'?'Orientation':l.kind==='workshop'?'Observe · read · practise':'Reading practice'}</small></span>{!enabled&&<span className="locked" aria-label="Complete the previous lesson to unlock">·</span>}</button></li>;})}</ol><p className="chapter-note">Start any chapter. Within a chapter, each lesson prepares you for the next.</p></aside></div></>;
}
