import {attemptId} from "../progress/attemptId";
import {useState} from "react";import {dueCards} from "../progress/review";import type {ReviewCard} from "../progress/types";import type {ProgressApi} from "../progress/useProgress";import {signById} from "../content/signs";import DrawingPad from "../writing/DrawingPad";import RecognitionPrompt from "../learning/RecognitionPrompt";import {makePrompt} from "../learning/prompts";
function ReviewQuestion({card,api,extra,onNext,pool,turn}:{card:ReviewCard;api:ProgressApi;extra:boolean;onNext:(correct:boolean)=>void;pool:string[];turn:number}){
 const [id]=useState(()=>attemptId()),[result,setResult]=useState<boolean|null>(null),[prompt]=useState(()=>makePrompt(card.signId,pool,turn%2?"reading-to-sign":"sign-to-reading",id));
 const answer=(correct:boolean)=>{api.submitOutcome({attemptId:id,signId:card.signId,skill:card.skill,correct,now:Date.now(),extra});setResult(correct);};
 if(card.skill==="recognition")return <RecognitionPrompt prompt={prompt} onAnswer={answer} onContinue={()=>onNext(result??false)}/>;
 return <><DrawingPad sign={signById[card.signId]} mode="memory" allowRepeat={false} onAssess={answer}/>{result!==null&&<button className="primary full review-next" onClick={()=>onNext(result)}>Continue →</button>}</>;
}
export default function ReviewView({api,onLearn}:{api:ProgressApi;onLearn:()=>void}){
 const [queue,setQueue]=useState<ReviewCard[]|null>(null),[extra,setExtra]=useState(false),[count,setCount]=useState(0),[turn,setTurn]=useState(0);
 const due=dueCards(api.progress,Date.now()),known=Object.values(api.progress.cards),pool=[...new Set(known.map(c=>c.signId))],card=queue?.[0];
 const start=(practice:boolean)=>{setExtra(practice);setQueue((practice?known:due).slice(0,10));setCount(0);setTurn(0);};
 const next=(correct:boolean)=>{setQueue(q=>{if(!q?.length)return [];const [current,...rest]=q;if(!correct)rest.splice(Math.min(2,rest.length),0,current);return rest;});setCount(n=>n+1);setTurn(t=>t+1);};
 return <><header className="page-header"><p className="eyebrow">A LITTLE, OFTEN</p><h1>Keep the signs close.</h1><p className="muted">Recall builds with each return.</p></header><section className="panel review-panel">{card?<><div className="between"><p className="eyebrow">{card.skill==="writing"?"WRITING RECALL":"SIGN RECOGNITION"}</p><button className="quiet" onClick={()=>setQueue([])}>End session</button></div><ReviewQuestion key={turn} card={card} api={api} extra={extra} onNext={next} pool={pool.length>1?pool:["a","e","i","o","u"]} turn={turn}/><p className="small muted review-count">{count} attempts completed · {queue!.length} remaining</p></>:queue!==null?<div className="empty-state"><span className="completion-mark">✓</span><h2>A good place to pause.</h2><p>{count} {count===1?"attempt":"attempts"} recorded. Come back when you’re ready.</p><button className="primary" onClick={()=>setQueue(null)}>Back to review</button></div>:<div className="empty-state"><div className="review-number">{due.length}</div><p className="eyebrow">CARDS READY TO REVISIT</p><h2>{due.length?"A few familiar faces.":known.length?"You’re up to date.":"Your collection starts here."}</h2><p>{due.length?"A short mix of recognition and writing, based on your practice.":known.length?"Nothing is due right now. A little extra practice is always welcome.":"Learn a sign or practise writing one. Your review cards will appear here."}</p>{due.length>0?<button className="primary" onClick={()=>start(false)}>Begin review →</button>:known.length?<button className="primary" onClick={()=>start(true)}>Practise learned signs →</button>:<button className="primary" onClick={onLearn}>Go to the first lesson →</button>}<p className="small muted review-explainer">Recognition and writing are reviewed separately. Extra practice keeps future review dates unchanged.</p></div>}</section></>;
}
