import {attemptId} from '../progress/attemptId';
import {useState} from 'react';
import {signs,signById} from '../content/signs';
import {studioExercises} from '../content/studio';
import type {ProgressApi} from '../progress/useProgress';
import DrawingPad,{type WriteMode} from '../writing/DrawingPad';
export default function WriteView({api,initialSign='a'}:{api:ProgressApi;initialSign?:string}){
 const [selected,setSelected]=useState(initialSign),[mode,setMode]=useState<WriteMode>('trace'),[kind,setKind]=useState('sign'),[exercise,setExercise]=useState(studioExercises[0].id);
 const sign=signById[selected]??signs[0],index=signs.findIndex(s=>s.id===sign.id),target=kind==='sign'?undefined:studioExercises.find(e=>e.id===exercise)!;
 return <><header className="page-header workbench-heading"><p className="eyebrow">WORKBENCH / {target?'LONG TABLET':'SIGN STUDY'}</p><h1>The writing table.</h1><p className="muted">Incise a sign. Compare the form. Smooth the clay and try again.</p></header>
 <div className="studio-layout"><section className="panel writing-panel"><div className="studio-tabs segmented" aria-label="Practice format"><button aria-pressed={kind==='sign'} onClick={()=>setKind('sign')}>Single sign</button><button aria-pressed={kind==='tablet'} onClick={()=>setKind('tablet')}>Words & records</button></div><div className="studio-top"><label>{target?'Choose a tablet':'Choose a sign'}{target?<select value={exercise} onChange={e=>setExercise(e.target.value)}>{studioExercises.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select>:<select value={sign.id} onChange={e=>setSelected(e.target.value)}>{signs.map(s=><option key={s.id} value={s.id}>{s.id} · {s.number}</option>)}</select>}</label><div className="segmented" aria-label="Writing mode">{(['trace','copy','memory'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='memory'?'Recall':m[0].toUpperCase()+m.slice(1)}</button>)}</div></div>
 {target&&<p className="tablet-task">{target.note}</p>}
 <DrawingPad key={(target?.id??sign.id)+mode} sign={sign} target={target} mode={mode} assessmentLabel={target?'Tablet practice complete.':'Practice recorded.'} onAssess={correct=>{if(!target)api.submitOutcome({attemptId:attemptId(),signId:sign.id,skill:'writing',correct,now:Date.now(),extra:true});}}/>
 {!target&&<div className="between"><button className="quiet" disabled={!index} onClick={()=>setSelected(signs[index-1].id)}>← Previous</button><button className="quiet" onClick={()=>setSelected(signs[(index+1)%signs.length].id)}>Next sign →</button></div>}</section>
 <aside className="studio-aside"><div className="sign-card"><span className="eyebrow">{target?'REFERENCE / SEQUENCE':'CATALOGUE / '+sign.number}</span>{mode!=='memory'?<span className={'sign specimen'+(target?' sequence-specimen':'')}>{target?target.glyphs.join(' '):sign.glyph}</span>:<div className="memory-mark" aria-hidden="true">?</div>}<h2>{target?.title??sign.id}</h2><p className="muted">{mode==='memory'?'The specimen is hidden until you compare.':target?.note??sign.note}</p></div>{target&&<div className="tip"><a href={target.sourceUrl} className="source-link" target="_blank" rel="noreferrer">Source for the practice model ↗</a></div>}</aside></div></>;
}
