import {judsonSource,numberSource,objectSource} from './tablets';
export interface Workshop {id:string;title:string;chapter:string;brief:string[];specimen:string;question:string;options:string[];answer:string;explanation:string;task:string;writingId?:string;tabletId?:string;sourceUrl:string;sourceTitle:string}
const cambridge='https://www.classics.cam.ac.uk/system/files/documents/process.pdf';
const liber='https://liber.cnr.it/tablet/view/5344';
export const chapters=[
 {id:'foundations',number:'I',title:'First impressions',description:'59 signs. Recognition, tracing and recall.'},
 {id:'spelling',number:'II',title:'Words & spelling',description:'Read the writing without treating it as an alphabet.'},
 {id:'accounts',number:'III',title:'Palace accounts',description:'Identify a thing. Read its quantity.'},
 {id:'tablets',number:'IV',title:'Read the tablets',description:'Work through three documented records.'},
 {id:'scribe',number:'V',title:'Scribe’s practice',description:'Use the whole surface to write a short record.'}
];
export const workshops:Workshop[]=[
 {id:'spelling-final',chapter:'spelling',title:'What a word leaves out',brief:['Word-final consonants are normally omitted. In a-mi-ni-so, the final s of Amnisos has no separate sign.','Transliteration follows the signs; interpretation identifies the word.'],specimen:'𐀀𐀖𐀛𐀰',question:'Which is the written sign sequence?',options:['a-mi-ni-so','Amnisos','a-mi-ni-s'],answer:'a-mi-ni-so',explanation:'Use one transliteration label per written sign.',task:'Copy a-mi-ni-so across a long tablet.',writingId:'a-mi-ni-so',sourceUrl:judsonSource,sourceTitle:'Judson · spelling conventions'},
 {id:'spelling-clusters',chapter:'spelling',title:'Between two consonants',brief:['The start of ti-ri-po-de represents a consonant cluster with two syllabic signs. Spelling vowels do not all correspond to separately spoken vowels.'],specimen:'𐀴𐀪𐀡𐀆',question:'Which pair begins the written word?',options:['ti-ri','ta-ra','te-re'],answer:'ti-ri',explanation:'The first two signs are ti and ri.',task:'Copy the four signs of ti-ri-po-de.',writingId:'ti-ri-po-de',sourceUrl:judsonSource,sourceTitle:'Judson · syllables and spelling'},
 {id:'spelling-sounds',chapter:'spelling',title:'A label is not every sound',brief:['The r-series can represent both r and l. Conventional labels simplify a writing system that does not mark every sound distinction.'],specimen:'𐀨 𐀩 𐀪 𐀫 𐀬',question:'Does an r-series label guarantee an r sound in the word?',options:['No; it can also represent l','Yes, always','It is only a number'],answer:'No; it can also represent l',explanation:'Read the label first; interpreting the word needs context.',task:'Practise a complete place-name sequence.',writingId:'ko-no-so',sourceUrl:judsonSource,sourceTitle:'Judson · sound values'},
 {id:'accounts-numbers',chapter:'accounts',title:'Read the quantity',brief:['These numbers add together. The two groups in the specimen are 50 and 7.','Keep groups legible: quantity is part of the record, not a decoration.'],specimen:'𐄔𐄍',question:'What quantity does the specimen record?',options:['57','75','507'],answer:'57',explanation:'50 + 7 = 57.',task:'Read the quantities in a flock record.',tabletId:'knossos-sheep',sourceUrl:numberSource,sourceTitle:'Unicode · Aegean Numbers'},
 {id:'accounts-goods',chapter:'accounts',title:'An object and a number',brief:['The specimen pairs the wheeled-chariot sign with the number 2. The object sign identifies what is counted.','This short exercise was composed for practice; it is not a tablet quotation.'],specimen:'𐃌 𐄈',question:'What does the first sign identify?',options:['A wheeled chariot','The number two','A vowel'],answer:'A wheeled chariot',explanation:'B240 identifies the chariot; the following numeral gives the quantity.',task:'Write the chariot sign followed by 2.',writingId:'chariot-2',sourceUrl:objectSource,sourceTitle:'Unicode · B240 and object signs'},
 {id:'tablet-workers-lesson',chapter:'tablets',title:'People in a record',brief:['PY Aa 62 lists women and children. Notice the separate entries and the numbers beside them.'],specimen:'𐀒𐀷 𐄐',question:'The word ko-wa identifies girls. How many follow it here?',options:['10','6','7'],answer:'10',explanation:'The horizontal numeral represents ten.',task:'Read the selected record in stages.',tabletId:'pylos-workers',sourceUrl:judsonSource,sourceTitle:'Judson · PY Aa 62'},
 {id:'tablet-flock-lesson',chapter:'tablets',title:'Two groups of sheep',brief:['KN De 1112 distinguishes male and female sheep with different animal signs. Keep each number with its own sign.'],specimen:'𐂇 𐄔𐄍   𐂆 𐄑𐄉',question:'Which quantity belongs to the female sheep, the second group?',options:['23','57','80'],answer:'23',explanation:'The second animal sign is followed by 20 + 3.',task:'Reveal and interpret line A.',tabletId:'knossos-sheep',sourceUrl:judsonSource,sourceTitle:'Judson · KN De 1112'},
 {id:'tablet-vessels-lesson',chapter:'tablets',title:'Words beside pictures',brief:['PY Ta 641 begins its second line with qe-to, vessel sign *203, and 3. The word, object sign and quantity each contribute to the entry.'],specimen:'𐀤𐀵 𐃢 𐄉',question:'Which sequence transliterates the two syllabic signs?',options:['qe-to','ko-no','ti-ri'],answer:'qe-to',explanation:'The signs are qe and to; the vessel and numeral are separate elements.',task:'Examine the opening of line 2.',tabletId:'pylos-vessels',sourceUrl:liber,sourceTitle:'LiBER · PY Ta 641, line 2'},
 {id:'scribe-place',chapter:'scribe',title:'Write a place name',brief:['The identification of ko-no-so with Knossos helped the decipherment. Now write the sequence as a connected exercise.','Leave a little space between signs; the task is a word, not one combined shape.'],specimen:'𐀒𐀜𐀰',question:'Which conventional reading belongs to this sequence?',options:['ko-no-so','a-mi-ni-so','ti-ri-po-de'],answer:'ko-no-so',explanation:'These are the three signs for the place name Knossos.',task:'Copy the name, compare the signs, then assess your work.',writingId:'ko-no-so',sourceUrl:cambridge,sourceTitle:'Cambridge · place names and decipherment'},
 {id:'scribe-record',chapter:'scribe',title:'Make a short teaching record',brief:['Use the bronze sign, followed by the numeral 10. This is a modern symbol-and-number exercise; it supplies no historical weight unit.','Check the object sign and the number separately before you finish.'],specimen:'𐂚 𐄐',question:'Which order matches this exercise?',options:['Bronze sign, then 10','10, then a place name','Two syllabic signs'],answer:'Bronze sign, then 10',explanation:'Write the material sign first and the requested number second.',task:'Write bronze followed by 10 on the clay.',writingId:'bronze-10',sourceUrl:objectSource,sourceTitle:'Unicode · B140 bronze'}
];
