export function workerSource(files,version){return `/* Generated by build-offline.mjs. All URLs are relative to this app. */
const scope = self.registration.scope;
const prefix = 'linear-b:' + new URL(scope).pathname + ':';
const cacheName = prefix + ${JSON.stringify(version)};
const urls = ${JSON.stringify(files)}.map(file => new URL(file, scope).href);
const home = new URL('index.html', scope).href;
self.addEventListener('install', event => {
 event.waitUntil(caches.open(cacheName).then(cache => cache.addAll(urls)));
});
self.addEventListener('activate', event => {
 event.waitUntil((async () => {
  for (const name of await caches.keys()) if (name.startsWith(prefix) && name !== cacheName) await caches.delete(name);
  await self.clients.claim();
 })());
});
self.addEventListener('message', event => {
 if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
self.addEventListener('fetch', event => {
 const url = new URL(event.request.url);
 if (event.request.method !== 'GET' || url.origin !== new URL(scope).origin || !url.href.startsWith(scope)) return;
 event.respondWith((async () => {
  const cache = await caches.open(cacheName);
  // Keep HTML and its hashed assets on the same installed version.
  if (event.request.mode === 'navigate') {
   const page = await cache.match(home);
   if (page) return page;
  }
  const cached = await cache.match(event.request);
  if (cached) return cached;
  return fetch(event.request);
 })());
});
`;}
