import OfflineStatus from "./offline/OfflineStatus";
import {flushSync} from "react-dom";
import {registerLearningTools,type ModelContext} from "./agent/tools";
import {useEffect,useRef,useState} from "react";
import {ensureLinearBFont} from "./writing/font";import {useProgress} from "./progress/useProgress";import {dueCards} from "./progress/review";import WriteView from "./views/WriteView";import LearnView from "./views/LearnView";import ReviewView from "./views/ReviewView";import Icon from "./ui/Icon";import SignsView from "./views/SignsView";import ReadView from "./views/ReadView";import PrintSheet from "./views/PrintSheet";import {lessons} from "./content/lessons";import "./print.css";
export default function App(){
 const api=useProgress(),[view,setView]=useState("learn"),[ready,setReady]=useState(false),[error,setError]=useState(false);
 const load=()=>{setError(false);ensureLinearBFont().then(()=>setReady(true)).catch(()=>setError(true));};useEffect(load,[]);
 const [writeSign,setWriteSign]=useState("a"),[printIds,setPrintIds]=useState<string[]|null>(null),[printError,setPrintError]=useState(false);
 useEffect(()=>{const end=()=>setPrintIds(null);window.addEventListener("afterprint",end);return()=>window.removeEventListener("afterprint",end);},[]);
 useEffect(()=>{if(!printIds)return;let cancelled=false;let frame=0;ensureLinearBFont().then(()=>{if(!cancelled)frame=requestAnimationFrame(()=>window.print());}).catch(()=>{if(!cancelled){setPrintError(true);setPrintIds(null);}});return()=>{cancelled=true;cancelAnimationFrame(frame);};},[printIds]);
 const print=(ids:string[])=>{setPrintError(false);setPrintIds(ids);};
 const [writeRequest,setWriteRequest]=useState(0);
 const agentState=useRef({api,ready});agentState.current={api,ready};
 useEffect(()=>registerLearningTools((document as Document&{modelContext?:ModelContext}).modelContext,()=>({completedLessons:agentState.current.api.progress.completedLessonIds.length,dueCards:dueCards(agentState.current.api.progress,Date.now()).length}),id=>{if(!agentState.current.ready)throw new Error("The sign font is not ready. Use the visible retry control if loading failed.");flushSync(()=>{setWriteSign(id);setWriteRequest(n=>n+1);setView("write");});window.scrollTo(0,0);}),[]);
 const currentLesson=lessons.find(l=>l.id===api.progress.cursor?.lessonId);
 const defaultPrint=view==="write"?[writeSign]:currentLesson?.kind==="signs"?currentLesson.signIds:["a","e","i","o","u"];
 const due=dueCards(api.progress,Date.now()).length;
 return <><div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-symbol">LB</span><div>Linear B<span>THE SCRIBE’S WORKBENCH</span></div></div><nav aria-label="Main navigation">{["learn","write","review","signs","read"].map(v=><button key={v} className={view===v?"nav-button active":"nav-button"} aria-current={view===v?"page":undefined} onClick={()=>{setView(v);window.scrollTo(0,0);}}><Icon name={v}/><span className="nav-label">{v[0].toUpperCase()+v.slice(1)}</span>{v==="review"&&due>0&&<span className="nav-count">{due}</span>}</button>)}</nav><div className="sidebar-foot">Signs. Words. Records.<br/><span>A study of the Mycenaean script.</span></div></aside><div className="main-column"><div className="topbar"><span>THE MYCENAEAN SCRIPT</span><span>59 SIGNS / {lessons.length} LESSONS</span></div><main className="main-content">{error?<div role="alert" className="panel"><h1>The signs could not load.</h1><p>Check your connection, then try again.</p><button className="primary" onClick={load}>Try again</button></div>:!ready?<p role="status">Loading the signs…</p>:view==="write"?<WriteView key={writeSign+writeRequest} api={api} initialSign={writeSign}/>:view==="review"?<ReviewView api={api} onLearn={()=>setView("learn")}/>:view==="signs"?<SignsView onWrite={id=>{setWriteSign(id);setView("write");window.scrollTo(0,0);}} onPrint={print}/>:view==="read"?<ReadView completedLessonIds={api.progress.completedLessonIds}/>:<LearnView api={api} onPrint={print}/>}{printError&&<p role="alert">The practice sheet could not load its signs. Check your connection and try printing again.</p>}<OfflineStatus/><footer className="progress-status" role="status">{api.storageStatus==="ok"?"Progress is saved in this browser on this device.":api.storageStatus==="blocked"?"You can keep practising, but this session’s progress cannot be saved.":"Your existing saved data was left unchanged. You can practise in this session, but these changes won’t be saved."}</footer></main></div></div><PrintSheet signIds={printIds??defaultPrint}/></>;
}
